### ISSUE TITLE
Document common commands via composer run-script

### ISSUE THREAD

**Issue by flavius** [wolfenste/tictactoe#19]
https://getcomposer.org/doc/articles/scripts.md#running-scripts-manually

For running tests in common scenarios (just unit tests, or also +integration, and/or with coverage), provide `scripts` in composer.json.

Just the commands which you use commonly, not all possible combinations.

It should be easy for others to deduce how you're working and start working in the same manner as you do.

**Comment by wolfenste** [comment]
Still, it is not the requested classification of tests.
