### ISSUE TITLE
Map should store the array of Marks.

### ISSUE THREAD

**Issue by flavius** [wolfenste/tictactoe#8]
Map should hold its own state in terms of Mark objects.

There are roughly two approaches:

1. Mark accepts only '0' or 'X' in its constructor, and Map stores an array of fixed size 9 with `null` or Mark instances
2. Mark accepts '0', 'X' or a special symbol for "empty square", and Map stores an array of fixed size 9 of Mark('special symbol here') by default, with Mark('0') or Mark('X') where the players have placed their symbols.

**Comment by wolfenste** [comment]
I guess this one will be closed when the Mark class will be defined.

**Comment by flavius** [comment]
Yes. Keep it as a reminder.
